### ISSUE TITLE
Add additional TFM so dependencies can be reduced

### ISSUE THREAD

**Issue by thompson-tomo** [ssg/TurkishId#10]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
The System.Runtime.CompilerServices.Unsafe package becomes conditional so only added for the older frameworks.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by ssg** [comment]
Why do you want to minimize your dependencies to non-framework packages? What's the actual problem?

**Comment by thompson-tomo** [comment]
it does 2 things, reduce compilation size and reduces chance of CVE's/conflicting versions. Think of those dependencies like System.IO you don't need to add that package if you want access to the file system due to the framework already guranteeing that the library will be available.

**Comment by ssg** [comment]
This unnecessarily complicates the build and dependency system (two framework targets instead of one), and the case presented here isn't convincing enough about any potential issues with it.

This can be achieved in a later version where .NET Standard 2.1 is fully deprecated by moving dependency into a current framework version. Until then, no need to add this complexity to the build system.
